# Generated by Django 5.1.4 on 2025-01-02 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinedistribution',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
