# Generated by Django 5.1.3 on 2025-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_medicine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
